management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,env

logging:
  level:
    org:
      springframework: INFO
    com:
      datastax: ERROR
    io:
      netty: ERROR
    reactor:
      netty: ERROR

spring:
  application:
    name: gacha-gateway
  cloud:
    gateway:
      routes:
      - id: gacha
        uri: lb://gacha-service
        predicates:
        - Path=/gachas/**
      - id: user
        uri: lb://user-service
        predicates:
        - Path=/users/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
# if we don't say anything in 2 seconds, there is something wrong with me
  instance:
    lease-expiration-duration-in-seconds: 2
# heartbeat every second
    lease-renewal-interval-in-seconds: 1